---
- hosts: all
  sudo: yes
  tasks:
  - name: Install required packages
    action: pacman pkg={{ item }} state=installed
    with_items:
      - lxc
      - bridge-utils
      - arch-install-scripts
      - netctl
      - rsync
  handlers:
    - name: restart ntpd
      action: service name=ntpd state=restarted
